POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjU2MDk2YmZmMGNmMWYzZjhkOTQyNTE5IiwiaWF0IjoxNzAwODMwMDI3LCJleHAiOjE3MDA4MzM2Mjd9.1wDqIxZsYTotAI65QwN9iL7rFmvueQKX2tq5bRvtXmo

{
	"title": "The Pragmatic Engineer",
	"author": "Gergely Orosz",
	"url": "https://newsletter.pragmaticengineer.com/",
	"likes": 10
}